import type { Account, Budget, Goal, Notice, Transaction } from "./types";

function iso(y: number, m: number, d: number, h = 12, min = 0) {
  return new Date(y, m - 1, d, h, min).toISOString();
}

export const SEED_ACCOUNTS: Account[] = [
  {
    id: "acc-checking",
    name: "Checking",
    institution: "Chase",
    type: "checking",
    balance: 14210.57,
  },
  {
    id: "acc-savings",
    name: "Savings",
    institution: "Ally",
    type: "savings",
    balance: 11880.15,
  },
  {
    id: "acc-credit",
    name: "Credit Card",
    institution: "Amex",
    type: "credit",
    balance: -1240.3,
  },
  {
    id: "acc-invest",
    name: "Investment",
    institution: "Fidelity",
    type: "investment",
    balance: 45680,
  },
];

export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    accountId: "acc-checking",
    merchant: "Northwind Payroll",
    amount: 3850,
    category: "salary",
    date: iso(2026, 8, 23, 9, 15),
  },
  {
    id: "tx-2",
    accountId: "acc-checking",
    merchant: "Studio invoice",
    amount: 2390,
    category: "salary",
    date: iso(2026, 8, 8, 11, 2),
  },
  {
    id: "tx-3",
    accountId: "acc-credit",
    merchant: "Urban Bistro",
    amount: -32.5,
    category: "food",
    date: iso(2026, 8, 24, 19, 42),
  },
  {
    id: "tx-4",
    accountId: "acc-credit",
    merchant: "Uber Ride",
    amount: -18.9,
    category: "transport",
    date: iso(2026, 8, 24, 17, 31),
  },
  {
    id: "tx-5",
    accountId: "acc-checking",
    merchant: "Amazon",
    amount: -67.49,
    category: "shopping",
    date: iso(2026, 8, 22, 20, 7),
  },
  {
    id: "tx-6",
    accountId: "acc-credit",
    merchant: "Shell Fuel",
    amount: -45,
    category: "transport",
    date: iso(2026, 8, 22, 18, 18),
  },
  {
    id: "tx-7",
    accountId: "acc-checking",
    merchant: "Whole Foods",
    amount: -128.4,
    category: "food",
    date: iso(2026, 8, 20, 16, 10),
  },
  {
    id: "tx-8",
    accountId: "acc-checking",
    merchant: "PG&E",
    amount: -142,
    category: "bills",
    date: iso(2026, 8, 18, 8, 0),
  },
  {
    id: "tx-9",
    accountId: "acc-checking",
    merchant: "Net",
    amount: -18.99,
    category: "entertainment",
    date: iso(2026, 8, 15, 7, 12),
  },
  {
    id: "tx-10",
    accountId: "acc-credit",
    merchant: "Apple Store",
    amount: -189,
    category: "shopping",
    date: iso(2026, 8, 14, 15, 40),
  },
  {
    id: "tx-11",
    accountId: "acc-checking",
    merchant: "Blue Bottle",
    amount: -6.75,
    category: "food",
    date: iso(2026, 8, 13, 8, 22),
  },
  {
    id: "tx-12",
    accountId: "acc-checking",
    merchant: "BART",
    amount: -86,
    category: "transport",
    date: iso(2026, 8, 12, 9, 5),
  },
  {
    id: "tx-13",
    accountId: "acc-checking",
    merchant: "Spotify",
    amount: -11.99,
    category: "entertainment",
    date: iso(2026, 8, 11, 6, 0),
  },
  {
    id: "tx-14",
    accountId: "acc-checking",
    merchant: "Landlord LLC",
    amount: -1850,
    category: "housing",
    date: iso(2026, 8, 1, 9, 0),
  },
  {
    id: "tx-15",
    accountId: "acc-checking",
    merchant: "Trader Joe's",
    amount: -64.2,
    category: "food",
    date: iso(2026, 8, 9, 18, 30),
  },
  {
    id: "tx-16",
    accountId: "acc-checking",
    merchant: "AT&T",
    amount: -89,
    category: "bills",
    date: iso(2026, 8, 5, 10, 0),
  },
  {
    id: "tx-17",
    accountId: "acc-checking",
    merchant: "Northwind Payroll",
    amount: 3850,
    category: "salary",
    date: iso(2026, 7, 23, 9, 15),
  },
  {
    id: "tx-18",
    accountId: "acc-checking",
    merchant: "Whole Foods",
    amount: -154.1,
    category: "food",
    date: iso(2026, 7, 19, 17, 0),
  },
  {
    id: "tx-19",
    accountId: "acc-checking",
    merchant: "Landlord LLC",
    amount: -1850,
    category: "housing",
    date: iso(2026, 7, 1, 9, 0),
  },
  {
    id: "tx-20",
    accountId: "acc-checking",
    merchant: "Northwind Payroll",
    amount: 3850,
    category: "salary",
    date: iso(2026, 6, 23, 9, 15),
  },
  {
    id: "tx-21",
    accountId: "acc-checking",
    merchant: "Landlord LLC",
    amount: -1850,
    category: "housing",
    date: iso(2026, 6, 1, 9, 0),
  },
  {
    id: "tx-22",
    accountId: "acc-checking",
    merchant: "Northwind Payroll",
    amount: 3700,
    category: "salary",
    date: iso(2026, 5, 23, 9, 15),
  },
  {
    id: "tx-23",
    accountId: "acc-checking",
    merchant: "Landlord LLC",
    amount: -1800,
    category: "housing",
    date: iso(2026, 5, 1, 9, 0),
  },
  {
    id: "tx-24",
    accountId: "acc-checking",
    merchant: "Northwind Payroll",
    amount: 3700,
    category: "salary",
    date: iso(2026, 4, 23, 9, 15),
  },
  {
    id: "tx-25",
    accountId: "acc-checking",
    merchant: "Landlord LLC",
    amount: -1800,
    category: "housing",
    date: iso(2026, 4, 1, 9, 0),
  },
  {
    id: "tx-26",
    accountId: "acc-checking",
    merchant: "Northwind Payroll",
    amount: 3600,
    category: "salary",
    date: iso(2026, 3, 23, 9, 15),
  },
  {
    id: "tx-27",
    accountId: "acc-checking",
    merchant: "Landlord LLC",
    amount: -1800,
    category: "housing",
    date: iso(2026, 3, 1, 9, 0),
  },
];

export const SEED_BUDGETS: Budget[] = [
  { id: "b-food", category: "food", limit: 600 },
  { id: "b-transport", category: "transport", limit: 250 },
  { id: "b-shopping", category: "shopping", limit: 400 },
  { id: "b-entertainment", category: "entertainment", limit: 150 },
  { id: "b-bills", category: "bills", limit: 280 },
];

export const SEED_GOALS: Goal[] = [
  {
    id: "g-emergency",
    name: "Emergency Fund",
    target: 12000,
    current: 8400,
    deadline: "2026-12-31",
  },
  {
    id: "g-laptop",
    name: "New Laptop",
    target: 1800,
    current: 1150,
    deadline: "2026-10-15",
  },
  {
    id: "g-vacation",
    name: "Vacation",
    target: 5000,
    current: 3200,
    deadline: "2026-11-01",
  },
  {
    id: "g-house",
    name: "House Down Payment",
    target: 50000,
    current: 22500,
    deadline: "2028-03-01",
  },
];

export const SEED_NOTICES: Notice[] = [
  {
    id: "n-1",
    title: "Amex payment due",
    body: "Minimum payment of $45 is due in 4 days.",
    date: iso(2026, 8, 31, 8, 0),
    read: false,
  },
  {
    id: "n-2",
    title: "Shopping budget at 80%",
    body: "You have $80 remaining in Shopping this month.",
    date: iso(2026, 8, 28, 12, 0),
    read: false,
  },
  {
    id: "n-3",
    title: "Salary deposited",
    body: "Northwind Payroll +$3,850.00 posted to Checking.",
    date: iso(2026, 8, 23, 9, 20),
    read: true,
  },
];
